name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        git submodule update --init --recursive
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
    - name: Test
      run: |
        cd build
        make test
